stages:
  - lint
  - test
  - coverage

variables:
  NODE_ENV: test

cache:
  paths:
    - node_modules/

lint:
  stage: lint
  image: node:20
  script:
    - npm ci
    - npm run lint
  only:
    - branches
    - merge_requests

test:
  stage: test
  image: node:20
  script:
    - npm ci
    - npm test
  artifacts:
    when: always
    paths:
      - coverage/
    reports:
      junit: coverage/junit.xml
  only:
    - branches
    - merge_requests

coverage:
  stage: coverage
  image: node:20
  script:
    - npm ci
    - npm run coverage
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week
  only:
    - branches
    - merge_requests